version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      dotnet-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/src/mPanel.Web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      nuxt-ecosystem:
        patterns:
          - "nuxt"
          - "@nuxt/*"
          - "vue"
          - "vue-router"
      npm-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "nuxt"
          - "@nuxt/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/src/mPanel.Node"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      actions-all:
        patterns:
          - "*"
