name: Tests

permissions:
  contents: read
  actions: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test tests/mPanel.Tests.API/mPanel.Tests.API.csproj --no-build --verbosity normal --logger "trx;LogFileName=api-tests-report.trx"

      - name: Publish report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Integration tests
          path: "**/api-tests-report.trx"
          reporter: dotnet-trx
          fail-on-error: false

  browser:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install browsers
        run: pwsh tests/mPanel.Tests.Web/bin/Debug/net10.0/playwright.ps1 install --with-deps

      - name: Test
        run: dotnet test tests/mPanel.Tests.Web/mPanel.Tests.Web.csproj --no-build --verbosity normal --logger "trx;LogFileName=web-tests-report.trx"
        env:
          ASPIRE_ENABLE_CONTAINER_TUNNEL: true

      - name: Upload traces and videos
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-results
          path: tests/mPanel.Tests.Web/bin/Debug/net10.0/test-results/
          retention-days: 30

      - name: Publish report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Browser tests
          path: "**/web-tests-report.trx"
          reporter: dotnet-trx
          fail-on-error: false

